### ISSUE TITLE
Colors do not show

### ISSUE THREAD

**Issue by nicolas-marien** [graemeboy/rainbow-tabs#1]
Hi,
I've installed your package which seems really cool on a Windows machine running Atom 1.0.19 yet colors do not show in the tabs.
I have a the [seti icons](https://atom.io/packages/seti-icons) package installed which alters the tabs yet I disabled it and reloaded Atom and still no color.
I it helps I'm rocking the [Atom Matrial UI](https://atom.io/themes/atom-material-ui) with [Seti Syntax](https://atom.io/themes/seti-syntax) which may also alter the tabs.
Thank you.

**Comment by ck-jrd** [comment]
Having the same issue as above. Using Atom Material UI and One Dark syntax running on Mac OSX 10.10.

I've also tried switching themes and syntaxes, to no avail.

**Comment by graemeboy** [comment]
Definitely a bug, sorry about that, just released this last night but I'll have a fix up soon.

**Comment by borgogelli** [comment]
It doesn't work

**Comment by nicolas-marien** [comment]
Okay, I did not see that the `rainbow-extensions:toggle` command had to be ran. With this things are working for me on OSX (I'll report for Windows in the morning).

EDIT: I checked on my Windows machine and everything is okay.
Sorry for the false alert. Yet it might be a good idea to update the README so that it's not mandatory to read the `package.json` to use this cool package :smile:

**Comment by graemeboy** [comment]
I have updated the plugin to automatically activate on atom loading. Sorry for the confusion.
